### PR TITLE
fix(laconia-event): only try to read body as Buffer if it isn't falsy

### LINKED ISSUE #49: WebSocket: Error 500 when using adapter for $connect route
**Describe the bug**
WebSocket adapter returns 500 without any error. I couldn't find what is causing the error as the error message is swallowed for $connect route.

**To Reproduce**

serverless.yml
```yml
  manage-connection:
    handler: src/manage-connection.handler
    events:
      - websocket:
          route: $connect
```

handler code:
```js
const laconia = require("@laconia/core");
const adapterApi = require("@laconia/adapter-api");

const app = async () => {};
const webSocket = adapterApi.webSocket();

exports.handler = laconia(webSocket(app));
```

**Expected behavior**
1. Return 200 as $connect is a happy path
2. Error message should be surfaced to the user

**Actual behavior**
1. Return 500
2. Error message is swallowed, I needed to go to `createWebSocketAdapter.js` and put a console.log inside `catch` block

The error message:
```
2019-06-02T19:48:59.072Z	296c7fe1-bf76-44bb-a958-79f9351af52e	TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
at Function.Buffer.from (buffer.js:183:11)
at module.exports.event (/var/task/node_modules/@laconia/adapter-api/node_modules/@laconia/event/src/apigateway/getBody.js:2:10)
at module.exports.event (/var/task/node_modules/@laconia/adapter-api/node_modules/@laconia/event/src/apigateway/parseWebSocket.js:5:16)
at fromRaw (/var/task/node_modules/@laconia/adapter-api/node_modules/@laconia/event/src/apigateway/ApiGatewayWebSocketEvent.js:10:7)
at /var/task/node_modules/@laconia/adapter-api/src/createWebSocketAdapter.js:5:30
at laconia (/var/task/node_modules/@laconia/core/src/laconia.js:30:28)
at <anonymous>
```

### PR DESCRIPTION
**Pull request by hugosenari**
WebSocket: Error 500 when using adapter for $connect route #49
The problem is create a buffer of event.body (undefined).

fix #49

### CODE REVIEW

File: packages/laconia-event/src/apigateway/parseWebSocket.js [hunk 1]
```diff
@@ -2,6 +2,6 @@ const getBody = require("./getBody");
 const tryParseJson = require("../tryParseJson");
 
 module.exports = event => {
-  const body = getBody(event);
+  const body = event.body && getBody(event);
```
Comment (hugosenari) [inline packages/laconia-event/src/apigateway/parseWebSocket.js]: Maybe a better solution would be make that verification at getBody
But this could change behavior of other events Adapters.
@geoffdutton any observation?

Comment (geoffdutton) [reply packages/laconia-event/src/apigateway/parseWebSocket.js]: Yeah my initial reaction would to put it in `getBody`, but then that poses the question, is `parseWebSocket.js` necessary?

I'm not as familiar with the website socket events. So an event can come from Lambda where the `.body` is undefined?

Comment (hugosenari) [reply packages/laconia-event/src/apigateway/parseWebSocket.js]: API Gateway websocket have at least 2 events:
- Connect (no body)
- Message (with body)
- Disconnect (??)

There are no well defined behavior if our user should set one handler for all these events or different handlers.

Comment (geoffdutton) [reply packages/laconia-event/src/apigateway/parseWebSocket.js]: Got it. I think what you have makes sense then considering a normal API Gateway event will always have a body. And then it makes sense to have a explicit `parseWebSocket` function as well because we might want to further parse out things specific to websockets. So I'd say you're good.
