### PR TITLE
Check for batch processing and trigger start event

### LINKED ISSUE #130: start event is fired on every recursion
**Describe the bug**
`@laconia/batch` fires `start` and `end` events. The `end` event is fired only once, when all the items have been processed. `start` event however is fired multiple times throughout the batch process i.e. everytime a Lambda is recursed.

**Expected behavior**
Start event is fired on the first time the batch processing is started

**Actual behavior**
Start event is fired on Lambda recursion

### PR DESCRIPTION
**Pull request by sakthivel-tw**
This fixes #130 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. 

- [x] shared-batch-handler-spec.js

### CODE REVIEW

File: packages/laconia-batch/src/laconiaBatch.js [hunk 1]
```diff
@@ -9,6 +9,10 @@ const forwardEvents = (from, eventNames, to, laconiaContext) => {
   );
 };
 
+const isBatchProcessingNotStarted = cursor => {
+  return cursor === undefined;
```
Comment (geoffdutton) [inline packages/laconia-batch/src/laconiaBatch.js]: Should we check for explicitly `undefined`, or is a falsy check good enough, I.e. 

```
const isBatchProcessingNotStarted = cursor => !cursor
```

And if so, do we need the extra function itself?

Comment (sakthivel-tw) [reply packages/laconia-batch/src/laconiaBatch.js]: Cursor being an object it makes sense to do a falsy check. 

Having it as a function makes it descriptive and easy to understand.

Comment (geoffdutton) [reply packages/laconia-batch/src/laconiaBatch.js]: Good point. It's either a function or a comment, and you might be able to reuse the function, or it might get more complex down the road.

**Comment by ceilfors** [comment]
Thank you for your contribution @sakthivel-tw!
